### ISSUE TITLE
createSObjectList not working for Leads

### ISSUE THREAD

**Issue by andykallio** [dhoechst/Salesforce-Test-Factory#9]
Hello,
I'm not much of a developer...more of an admin...so this is probably user error, but I have been using this with no problems for at least a year. Anyway, I need to set up some test lead records. There seems to be some issue with the createSobjectLIst methods because I can't seem to get around the following error message: Invalid field name for Lead. I can't figure out which field it is.  However, when I use createSObject it works fine. 

```
 static testMethod void leadDataPrivacyHandler() {
        //this one fails
        List<Lead> c1 = (List<Lead>)TestFactory.createSObjectList(new Lead( Email_Opt_In__c = true),2,true);
       
}
```

```
static testMethod void leadDataPrivacyHandler() {
//but the following lines don't fail
        Lead ca = (Lead)TestFactory.createSObject(new Lead(Email_Opt_In__c = true ),true);
        Lead cb = (Lead)TestFactory.createSObject(new Lead(Email_Opt_In__c = true ),true);
        List<Lead> c1 = new LIst<Lead>{ca,cb};
}

```

I added a method to the TestFactory class for LeadDefaults: 
```public class LeadDefaults implements FieldDefaults {
		public Map<String, Object> getFieldDefaults() {
            system.debug('getting lead defaults');
			return new Map<String, Object> {
				'FirstName' => 'First',
                'LastName' => 'Last',
                'Company' => 'test company',   
                'Business_Owner__c' => 'Pureprofile',
                'Email' => 'akalliolead@akalliotest.com'    
                    
			};
		}
	}
```

**Comment by aheber** [comment]
I'm guessing it is a problem with the nameFieldMap. If the SObject doesn't have a native field with an API name of `Name` then it must be overridden using the nameFieldMap. It is delivered with entries for Case and Contact but Lead would be another one, you would want to map it to the LastName field.

```
	// When we create a list of SObjects, we need to
	private static Map<String, String> nameFieldMap = new Map<String, String> {
		'Contact' => 'LastName',
		'Lead' => 'LastName',
		'Case' => 'Subject',
	};
```

**Comment by andykallio** [comment]
Thank you!!! Problem solved.
